#include "stm32f446xx.h"

void GPIO_Init(void) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOC->MODER &= ~(GPIO_MODER_MODER13_Msk);//SET PC13 TO INPUT
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD13_Msk);//CLEAR PUPDR REGISTER FOR PC13
	GPIOC->PUPDR |= (0X1U << GPIO_PUPDR_PUPD13_Pos);//SET PC13 TO PULLUP
	GPIOA->MODER &= ~(GPIO_MODER_MODER5_Msk);
	GPIOA->MODER |= (0X1U << GPIO_MODER_MODER5_Pos);//SET PA5 TO OUTPUT
}
int main(void) {
	GPIO_Init();

	while(1){
		if(!(GPIOC->IDR & GPIO_IDR_ID13)){

			GPIOA->BSRR = GPIO_BSRR_BS5;
		}
		else{

			GPIOA->BSRR = GPIO_BSRR_BR5;
		}

	}
}

